ALTER TABLE ACCOUNT 
ADD CONSTRAINT unq_account_name UNIQUE (NAME);

ALTER TABLE CATEGORY 
ADD CONSTRAINT unq_category_name UNIQUE (NAME,PRNT_CAT_ID,TRAN_TYPE),
ADD CONSTRAINT fk_category_prnt_id FOREIGN KEY (PRNT_CAT_ID) REFERENCES CATEGORY (ID ) ON DELETE CASCADE,
ADD CONSTRAINT fk_category_acct_id FOREIGN KEY (DFLT_ACCT_ID) REFERENCES ACCOUNT (ID ) ON DELETE SET NULL;

ALTER TABLE TRANSACTION
ADD CONSTRAINT fk_transaction_cat_id FOREIGN KEY (CAT_ID) REFERENCES CATEGORY (ID ),
ADD CONSTRAINT fk_transaction_acct_id FOREIGN KEY (ACCT_ID) REFERENCES ACCOUNT (ID );

ALTER TABLE TRANSACTION
ADD IS_REC			tinyint(1) DEFAULT 0;
ALTER TABLE TRANSACTION
ADD REC_WHEN		varchar(25);

ALTER TABLE BUDGET 
ADD CONSTRAINT unq_budget_name UNIQUE (NAME);

ALTER TABLE BUDGET_ITEM 
ADD CONSTRAINT unq_budget_cat UNIQUE (BUDGET_ID, CAT_ID),
ADD CONSTRAINT fk_category_id FOREIGN KEY (CAT_ID) REFERENCES CATEGORY (ID ) ON DELETE CASCADE,
ADD CONSTRAINT fk_budget_id FOREIGN KEY (BUDGET_ID) REFERENCES BUDGET (ID ) ON DELETE CASCADE;

ALTER TABLE BNK_STMNT 
ADD CONSTRAINT bnk_st_unq_name UNIQUE (NAME),
ADD CONSTRAINT fk_acct_id FOREIGN KEY (ACCT_ID) REFERENCES ACCOUNT (ID ) ON DELETE CASCADE;

ALTER TABLE BNK_STMNT_COL_MAP 
ADD CONSTRAINT fk_bnk_st_id FOREIGN KEY (BNK_STMNT_ID) REFERENCES BNK_STMNT (ID ) ON DELETE CASCADE;

ALTER TABLE BNK_STMNT_DATA_MAP 
ADD CONSTRAINT fk_data_bnk_st_id FOREIGN KEY (BNK_STMNT_ID) REFERENCES BNK_STMNT (ID ) ON DELETE CASCADE;

ALTER TABLE BNK_STMNT_DATA_FIELD 
ADD CONSTRAINT bnk_st_data_field_unq_prop UNIQUE (DATA_MAP_ID, PROP_NAME),
ADD CONSTRAINT fk_data_field_data_map_id FOREIGN KEY (DATA_MAP_ID) REFERENCES BNK_STMNT_DATA_MAP (ID ) ON DELETE CASCADE;

ALTER TABLE TRANSACTION ADD CHECKSUM VARCHAR(100);

ALTER TABLE TRANSACTION ADD FROM_ACCT_ID INT(20);

ALTER TABLE TRANSACTION
ADD CONSTRAINT fk_transaction_from_acct_id FOREIGN KEY (FROM_ACCT_ID) REFERENCES ACCOUNT (ID );

ALTER TABLE FUTURE_TRANSACTION
ADD CONSTRAINT fk_futuretransaction_tran_id FOREIGN KEY (TRAN_ID) REFERENCES TRANSACTION(ID);

ALTER TABLE MT_USER 
ADD CONSTRAINT unq_user_username UNIQUE (USERNAME);

ALTER TABLE MT_USER_ROLE 
ADD CONSTRAINT unq_userrole_role_user UNIQUE (USER_ID, ROLE_ID),
ADD CONSTRAINT fk_userrole_user_id FOREIGN KEY (USER_ID) REFERENCES MT_USER (ID );

ALTER TABLE IMPORTED_TRANSACTION 
ADD CONSTRAINT fk_imptran_tran_id FOREIGN KEY (TRAN_ID) REFERENCES TRANSACTION (ID ) ON DELETE CASCADE;

ALTER TABLE IMPORTED_TRANSACTION 
ADD CONSTRAINT unq_imptran_checksum UNIQUE (CHECKSUM);
