CREATE TABLE IF NOT EXISTS ACCOUNT (
	ID	INT(20) NOT NULL AUTO_INCREMENT,
	NAME 		varchar(50) NOT NULL,
	CRNT_BAL	decimal(20,2),
	ACCT_TYPE 	varchar(10) NOT NULL,
	DISPLAY		TINYINT(1),
	CREATED_DATE  datetime,
	MODIFIED_DATE datetime,
	
	PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CATEGORY (
	ID	INT(20) NOT NULL AUTO_INCREMENT,
	NAME 			varchar(50) NOT NULL,
	PRNT_CAT_ID		int(20),
	DFLT_ACCT_ID	int(20),
	TRAN_TYPE 		varchar(10) NOT NULL,
	DISPLAY			TINYINT(1),
	CREATED_DATE  	datetime NOW(),
	MODIFIED_DATE 	datetime NOW(),
	
	PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS TRANSACTION (
	ID	INT(20) 	NOT NULL AUTO_INCREMENT,
	ON_DATE  		datetime NOT NULL,
	AMOUNT			decimal(20,2) NOT NULL,
	CAT_ID			int(20) NOT NULL,
	ACCT_ID			int(20) NOT NULL,
	DESCRIPTION		varchar(255),
	CREATED_DATE  	datetime NOW(),
	MODIFIED_DATE 	datetime NOW(),
	
	PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SETTING (
	ID	INT(20) NOT NULL AUTO_INCREMENT,
	NAME 		varchar(50) NOT NULL,
	DESCRIPTION varchar(255),
	VALUE 		varchar(255) NOT NULL,
	TYPE		varchar(50),
	CREATED_DATE  datetime,
	MODIFIED_DATE datetime,
	
	PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BUDGET (
	ID	INT(20) NOT NULL AUTO_INCREMENT,
	NAME 		varchar(50) NOT NULL,
	CREATED_DATE  datetime,
	MODIFIED_DATE datetime,
	
	PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BUDGET_ITEM (
	ID	INT(20) NOT NULL AUTO_INCREMENT,
	BUDGET_ID		int(20) NOT NULL,
	CAT_ID			int(20) NOT NULL,
	AMOUNT			decimal(20,2) NOT NULL,
	PERIOD			varchar(2) DEFAULT 'M',
	CREATED_DATE  datetime,
	MODIFIED_DATE datetime,
	
	PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BNK_STMNT (
	ID	INT(20) NOT NULL AUTO_INCREMENT,
	NAME		varchar(35) NOT NULL,
	ACCT_ID		int(20) NOT NULL,
	DATE_FORMAT	varchar(30),
	START_ROW int(5) DEFAULT 1,
	
	CREATED_DATE  datetime,
	MODIFIED_DATE datetime,
	
	PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BNK_STMNT_COL_MAP (
	ID	INT(20) NOT NULL AUTO_INCREMENT,
	BNK_STMNT_ID		int(20) NOT NULL,
	PROP_NAME	varchar(25) NOT NULL,
	COL_NAME	varchar(10) NOT NULL,
	DATA_TYPE	varchar(10) NOT NULL DEFAULT 'text',
	
	CREATED_DATE  datetime,
	MODIFIED_DATE datetime,
	
	PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BNK_STMNT_DATA_MAP (
	ID	INT(20) NOT NULL AUTO_INCREMENT,
	BNK_STMNT_ID		int(20) NOT NULL,
	SEARCH_PROP_NAME	varchar(25) NOT NULL,
	SEARCH_TEXT			varchar(25) NOT NULL,
	
	CREATED_DATE  datetime,
	MODIFIED_DATE datetime,
	PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BNK_STMNT_DATA_FIELD (
	ID	INT(20) NOT NULL AUTO_INCREMENT,
	DATA_MAP_ID			int(20) NOT NULL,
	PROP_NAME			varchar(25) NOT NULL,
	DATA				varchar(100) NOT NULL,
	DATA_TYPE			varchar(10) NOT NULL DEFAULT 'text',
	
	CREATED_DATE  datetime,
	MODIFIED_DATE datetime,
	PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS FUTURE_TRANSACTION (
	ID			INT(20) NOT NULL AUTO_INCREMENT,
	TRAN_ID		INT(20) NOT NULL,
	
	PERIOD		varchar(1) NOT NULL DEFAULT 'M',
	HOW_MANY	INT(3) DEFAULT 1,
	CREATED_DATE  datetime,
	MODIFIED_DATE datetime,
	
	PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS IMPORT_STMNT (
	ID	INT(20) NOT NULL AUTO_INCREMENT,
	FILE_NAME	varchar(50) NOT NULL,
	ON_DATE		datetime,
	
	CREATED_DATE  datetime,
	MODIFIED_DATE datetime,
	
	PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS MT_USER (
	ID		INT(20) NOT NULL AUTO_INCREMENT,
	NAME 		varchar(50) NOT NULL,
	USERNAME 	varchar(50) NOT NULL,
	PASSWORD	varchar(255) NOT NULL,
	CREATED_DATE  datetime,
	MODIFIED_DATE datetime,
	
	PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS MT_USER_ROLE (
	ID		INT(20) NOT NULL AUTO_INCREMENT,
	ROLE_ID	varchar(3) NOT NULL DEFAULT 'U', -- User, Admin
	USER_ID	int(30) NOT NULL,
	CREATED_DATE  datetime,
	MODIFIED_DATE datetime,
	
	PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS IMPORTED_TRANSACTION (
	ID	INT(20) 	NOT NULL AUTO_INCREMENT,
	TRAN_ID			int(20) NOT NULL,
	CHECKSUM 		VARCHAR(100) NOT NULL,
	CREATED_DATE  datetime,
	MODIFIED_DATE datetime,
	
	PRIMARY KEY(ID)
)ENGINE=InnoDB;